
[jenkins_master]
jenkins_build ansible_host=172.31.25.190 ansible_user=ec2-user

[jenkins_agent]
jenkins_staging ansible_host=172.31.18.124 ansible_user=ubuntu

[db_server]
jenkins_app ansible_host=172.31.18.124 ansible_user=centos

[app_servers]
app1 ansible_host=172.31.18.124 ansible_user=centos

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
